
image:
  repository: yampss/hipstershop-adservice
  tag: latest

namespace: hipster-backend

replicas: 3

rollingUpdate:
  maxUnavailable: 1
  maxSurge: 1

service:
  port: 9555

resources:
  requests:
    cpu: 200m
    memory: 180Mi
  limits:
    cpu: 300m
    memory: 512Mi

probes:
  initialDelaySeconds: 60
  periodSeconds: 15
  healthPath: "/_healthz"
